// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDQNvxgp_jAQHHQJRjm3mQPKZVCPLWwg',
    appId: '1:571685134917:android:953548ec88c1287074392c',
    messagingSenderId: '571685134917',
    projectId: 'authproject-377b4',
    databaseURL: 'https://authproject-377b4.firebaseio.com',
    storageBucket: 'authproject-377b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBqxWIitwI_I541qtsgXqWiNOUJCf5Srg',
    appId: '1:571685134917:ios:8265afcd8282c97374392c',
    messagingSenderId: '571685134917',
    projectId: 'authproject-377b4',
    databaseURL: 'https://authproject-377b4.firebaseio.com',
    storageBucket: 'authproject-377b4.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBqxWIitwI_I541qtsgXqWiNOUJCf5Srg',
    appId: '1:571685134917:ios:8265afcd8282c97374392c',
    messagingSenderId: '571685134917',
    projectId: 'authproject-377b4',
    databaseURL: 'https://authproject-377b4.firebaseio.com',
    storageBucket: 'authproject-377b4.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7wfK0aiCBjIagpooWx4g1C30QCrT85Ko',
    appId: '1:571685134917:web:7b6b635ab2b9448174392c',
    messagingSenderId: '571685134917',
    projectId: 'authproject-377b4',
    authDomain: 'authproject-377b4.firebaseapp.com',
    databaseURL: 'https://authproject-377b4.firebaseio.com',
    storageBucket: 'authproject-377b4.firebasestorage.app',
  );

}